// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6pTCiHCTYXDxzo0weMv0MUp3WwY9CtM',
    appId: '1:877486999470:web:65700258cbbfaff94daa3f',
    messagingSenderId: '877486999470',
    projectId: 'wack-olumide',
    authDomain: 'wack-olumide.firebaseapp.com',
    storageBucket: 'wack-olumide.firebasestorage.app',
    measurementId: 'G-3HKBWPZWR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlSy-6QUQPZEzQPKV9hawcyzmtWVvoMc',
    appId: '1:877486999470:android:f1ceb1e6f422d12c4daa3f',
    messagingSenderId: '877486999470',
    projectId: 'wack-olumide',
    storageBucket: 'wack-olumide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsAlMe7aNhBPDuShnj1Pi0ql66q3X57q8',
    appId: '1:877486999470:ios:52644a477bf0ea394daa3f',
    messagingSenderId: '877486999470',
    projectId: 'wack-olumide',
    storageBucket: 'wack-olumide.firebasestorage.app',
    iosBundleId: 'com.example.wack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsAlMe7aNhBPDuShnj1Pi0ql66q3X57q8',
    appId: '1:877486999470:ios:52644a477bf0ea394daa3f',
    messagingSenderId: '877486999470',
    projectId: 'wack-olumide',
    storageBucket: 'wack-olumide.firebasestorage.app',
    iosBundleId: 'com.example.wack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh6pTCiHCTYXDxzo0weMv0MUp3WwY9CtM',
    appId: '1:877486999470:web:c6bf3d7ad2617f5b4daa3f',
    messagingSenderId: '877486999470',
    projectId: 'wack-olumide',
    authDomain: 'wack-olumide.firebaseapp.com',
    storageBucket: 'wack-olumide.firebasestorage.app',
    measurementId: 'G-DTSK1NY8QR',
  );
}
